from enum import Enum


class DisputeType(str, Enum):
    VERDICT = "VERDICT"
    SOURCE_QUALITY = "SOURCE_QUALITY"
    UNCERTAINTY = "UNCERTAINTY"


class DisputeStatus(str, Enum):
    PENDING = "PENDING"
    VALIDATED = "VALIDATED"
    REJECTED = "REJECTED"


class DisputeErrorCode(str, Enum):
    SELF_DISPUTE = "SELF_DISPUTE"
    ALREADY_DISPUTED = "ALREADY_DISPUTED"
    RATE_LIMIT_REACHED = "RATE_LIMIT_REACHED"
    ACCOUNT_TOO_NEW = "ACCOUNT_TOO_NEW"
    POST_UNDER_REVIEW = "POST_UNDER_REVIEW"
    POST_NOT_FOUND = "POST_NOT_FOUND"
